import { useState, useRef, useEffect } from "react"
import { useParams } from "react-router-dom"
import { createClient } from "@supabase/supabase-js"
import jsPDF from "jspdf"

const supabase = createClient("https://dmqgbxjnfkjnkpfirfdl.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcWdieGpuZmtqbmtwZmlyZmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxMDA0NzYsImV4cCI6MjA5MTY3NjQ3Nn0.y16FCg_HXkd7Ua_CU7K2o5Kd-QuEXxbz18hZsj4GaHI")
const ANTHROPIC_KEY = import.meta.env.VITE_ANTHROPIC_KEY

function exportGuestsPDF(guests, charterName) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  const addText = (text, x, size = 11, style = 'normal', color = [30, 30, 30]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, pageWidth - 2 * x)
    doc.text(lines, x, y)
    y += lines.length * (size * 0.45) + 2
  }

  const addLine = () => {
    doc.setDrawColor(220, 215, 205)
    doc.line(15, y, pageWidth - 15, y)
    y += 6
  }

  const checkPage = () => {
    if (y > 270) { doc.addPage(); y = 20 }
  }

  // Header
  doc.setFillColor(26, 58, 92)
  doc.rect(0, 0, pageWidth, 30, 'F')
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('THE GALLEY', 15, 18)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(charterName || 'Guest Profiles', pageWidth - 15, 18, { align: 'right' })
  y = 42

  guests.forEach((g, index) => {
    checkPage()

    // Guest name
    addText(g.name, 15, 16, 'bold', [26, 58, 92])
    y += 2

    if (g.allergies?.length) {
  addText(`ALLERGIES: ${g.allergies.join(', ')}`, 15, 10, 'bold', [180, 40, 40])
}
if (g.dislikes?.length) {
  addText(`DISLIKES: ${g.dislikes.join(', ')}`, 15, 10, 'normal', [120, 80, 40])
}
if (g.diets?.length) {
  addText(`DIET: ${g.diets.join(', ')}`, 15, 10, 'normal', [40, 100, 60])
}
    if (g.cuisines?.length) {
      addText(`Preferred cuisines: ${g.cuisines.join(', ')}`, 15, 10)
    }
    if (g.favorites) {
      addText(`Favourites: ${g.favorites}`, 15, 10)
    }

    y += 3
    // Meal times
    if (g.breakfast_time || g.lunch_time || g.dinner_time) {
      addText('MEAL TIMES', 15, 9, 'bold', [100, 100, 100])
      const times = []
     if (g.breakfast_time) times.push(`Breakfast: ${g.breakfast_time}`)
if (g.lunch_time) times.push(`Lunch: ${g.lunch_time}`)
if (g.dinner_time) times.push(`Dinner: ${g.dinner_time}`)
      addText(times.join('   |   '), 15, 10)
    }
    if (g.breakfast) addText(`Breakfast prefs: ${g.breakfast}`, 15, 10)
    if (g.juices) addText(`Juices: ${g.juices}`, 15, 10)

    y += 3
    // Drinks
    if (g.spirits || g.cocktails || g.softs) {
      addText('DRINKS', 15, 9, 'bold', [100, 100, 100])
      if (g.spirits) addText(`Spirits: ${g.spirits}`, 15, 10)
      if (g.cocktails) addText(`Cocktails: ${g.cocktails}`, 15, 10)
      if (g.softs) addText(`Softs: ${g.softs}`, 15, 10)
    }

    if (g.notes) {
      y += 2
      addText(`Notes: ${g.notes}`, 15, 10, 'italic', [80, 80, 80])
    }

    y += 6
    if (index < guests.length - 1) addLine()
    checkPage()
  })

  // Footer
  const today = new Date().toLocaleDateString('en-GB')
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 160)
  doc.text(`Generated by The Galley — ${today}`, pageWidth / 2, 290, { align: 'center' })

  doc.save(`the-galley-guests-${today}.pdf`)
}

function GuestCard({ g, isSelected, onToggle }) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div style={{marginBottom:'8px',border:`1px solid ${isSelected ? 'var(--accent)' : 'var(--border)'}`,borderRadius:'2px',background: isSelected ? 'var(--accent)' : '#fff',transition:'all .2s'}}>
      <div onClick={onToggle} style={{padding:'10px 12px',cursor:'pointer'}}>
        <div style={{display:'flex',alignItems:'center',gap:'8px'}}>
          <div style={{width:'16px',height:'16px',borderRadius:'3px',border:`1px solid ${isSelected ? '#fff' : 'var(--border)'}`,background: isSelected ? '#fff' : 'transparent',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>
            {isSelected && <span style={{color:'var(--accent)',fontSize:'12px',fontWeight:'bold'}}>✓</span>}
          </div>
          <div style={{flex:1}}>
            <div style={{fontFamily:'Cormorant Garamond, serif',fontSize:'17px',color: isSelected ? '#fff' : 'var(--ink)'}}>{g.name}</div>
            {g.allergies?.length > 0 && <div style={{fontSize:'11px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--danger)',marginTop:'3px'}}>⚠️ {g.allergies.join(', ')}</div>}
            {g.dislikes?.length > 0 && <div style={{fontSize:'11px',color: isSelected ? 'rgba(255,255,255,0.7)' : 'var(--muted)',marginTop:'2px'}}>🚫 {g.dislikes.join(', ')}</div>}
            {g.diets?.length > 0 && <div style={{fontSize:'11px',color: isSelected ? 'rgba(255,255,255,0.7)' : 'var(--accent)',marginTop:'2px'}}>🥗 {g.diets.join(', ')}</div>}
          </div>
          <div onClick={e => { e.stopPropagation(); setExpanded(!expanded) }} style={{fontSize:'11px',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',cursor:'pointer',padding:'2px 6px',border:`1px solid ${isSelected ? 'rgba(255,255,255,0.3)' : 'var(--border)'}`,borderRadius:'2px',flexShrink:0}}>
            {expanded ? '▲' : '▼'}
          </div>
        </div>
      </div>

      {expanded && (
        <div style={{padding:'0 12px 12px',borderTop:`1px solid ${isSelected ? 'rgba(255,255,255,0.2)' : 'var(--border)'}`,marginTop:'4px'}}>
          {(g.breakfast_time || g.lunch_time || g.dinner_time) && (
            <div style={{marginTop:'10px'}}>
              <div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'6px'}}>⏰ Meal Times</div>
              <div style={{display:'flex',gap:'12px',flexWrap:'wrap'}}>
                {g.breakfast_time && <span style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>🌅 {g.breakfast_time}</span>}
                {g.lunch_time && <span style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>☀️ {g.lunch_time}</span>}
                {g.dinner_time && <span style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>🌙 {g.dinner_time}</span>}
              </div>
            </div>
          )}
          {g.breakfast && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>🍳 Breakfast</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.breakfast}</div></div>}
          {g.juices && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>🥤 Juices</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.juices}</div></div>}
          {g.softs && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>🧃 Soft Drinks</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.softs}</div></div>}
          {g.spirits && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>🥃 Spirits</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.spirits}</div></div>}
          {g.cocktails && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>🍹 Cocktails</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.cocktails}</div></div>}
          {g.favorites && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>⭐ Favourites</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.favorites}</div></div>}
          {g.notes && <div style={{marginTop:'10px'}}><div style={{fontSize:'10px',fontWeight:'600',letterSpacing:'.1em',textTransform:'uppercase',color: isSelected ? 'rgba(255,255,255,0.6)' : 'var(--muted)',marginBottom:'4px'}}>📝 Notes</div><div style={{fontSize:'12px',color: isSelected ? 'rgba(255,255,255,0.9)' : 'var(--ink)'}}>{g.notes}</div></div>}
        </div>
      )}
    </div>
  )
}

export default function CrewPage() {
  const { token } = useParams()
  const [unlocked, setUnlocked] = useState(false)
  const [passwordInput, setPasswordInput] = useState('')
  const [passwordError, setPasswordError] = useState(false)
  const [yacht, setYacht] = useState(null)
  const [activeCharter, setActiveCharter] = useState(null)
  const [allGuests, setAllGuests] = useState([])
  const [selectedGuests, setSelectedGuests] = useState([])
  const [chatHistory, setChatHistory] = useState([])
  const [chatInput, setChatInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [messages, setMessages] = useState([])
  const chatBoxRef = useRef(null)

  useEffect(() => {
    if (chatBoxRef.current) chatBoxRef.current.scrollTop = chatBoxRef.current.scrollHeight
  }, [messages])

  useEffect(() => {
    const savedAuth = localStorage.getItem(`crewAuth_${token}`)
    if (savedAuth === 'true') { setUnlocked(true); fetchYachtAndGuests() }
  }, [token])

  const unlock = async () => {
    const { data } = await supabase.from('yachts').select('crew_password').eq('crew_token', token).single()
    if (data && passwordInput === (data.crew_password || 'crew2026')) {
      localStorage.setItem(`crewAuth_${token}`, 'true')
      setUnlocked(true)
      fetchYachtAndGuests()
    } else setPasswordError(true)
  }

  const fetchYachtAndGuests = async () => {
    const { data: yachtData } = await supabase.from('yachts').select('*').eq('crew_token', token).single()
    if (!yachtData) return
    setYacht(yachtData)
    const { data: charterData } = await supabase.from('charters').select('*').eq('yacht_id', yachtData.id).eq('active', true).single()
    if (charterData) {
      setActiveCharter(charterData)
      const { data: guestsData } = await supabase.from('guests').select('*').eq('charter_id', charterData.id).eq('archived', false)
      if (guestsData) setAllGuests(guestsData)
    }
  }

  const toggleSelectGuest = (g) => {
    setSelectedGuests(prev => {
      const exists = prev.find(s => s.id === g.id)
      return exists ? prev.filter(s => s.id !== g.id) : [...prev, g]
    })
    setMessages([])
    setChatHistory([])
  }

  const selectAll = () => { setSelectedGuests(allGuests); setMessages([]); setChatHistory([]) }
  const clearSelection = () => { setSelectedGuests([]); setMessages([]); setChatHistory([]) }

  const buildSystem = () => {
    if (selectedGuests.length === 0) return "You are the private chef assistant aboard an ultra-luxury superyacht. No guest selected. Respond in English, be concise and professional."

    const profiles = selectedGuests.map(p => [
      "GUEST: " + p.name,
      p.allergies?.length ? "⚠️ ALLERGIES: " + p.allergies.join(", ") : "",
      p.dislikes?.length  ? "🚫 DISLIKES: " + p.dislikes.join(", ") : "",
      p.diets?.length     ? "🥗 DIET: " + p.diets.join(", ") : "",
      p.cuisines?.length  ? "Loves: " + p.cuisines.join(", ") : "",
      p.favorites         ? "Favourites: " + p.favorites : "",
      p.spirits           ? "Spirits: " + p.spirits : "",
      p.cocktails         ? "Cocktails: " + p.cocktails : "",
      p.softs             ? "Softs: " + p.softs : "",
      p.breakfast         ? "Breakfast prefs: " + p.breakfast : "",
      p.breakfast_time    ? "Breakfast time: " + p.breakfast_time : "",
      p.lunch_time        ? "Lunch time: " + p.lunch_time : "",
      p.dinner_time       ? "Dinner time: " + p.dinner_time : "",
      p.juices            ? "Juices: " + p.juices : "",
      p.notes             ? "Notes: " + p.notes : "",
    ].filter(Boolean).join(" | ")).join("\n")

    return [
      "You are a private chef assistant aboard an ultra-luxury superyacht.",
      "",
      "GUEST PROFILES:",
      profiles,
      "",
      "═══════════════════════════════════════",
      "ABSOLUTE PRIORITY RULES — NEVER BREAK:",
      "═══════════════════════════════════════",
      "",
      "ALLERGIES, DISLIKES AND DIETARY REQUIREMENTS ARE ALL EQUAL PRIORITY.",
      "There is NO hierarchy between them. All three must be respected with zero tolerance.",
      "",
      "ALLERGIES: Never include. Not even in traces, sauce, garnish, or broth.",
      "DISLIKES: Never include. Not even in traces, sauce, garnish, or broth. Same as allergy.",
      "DIETARY REQUIREMENTS:",
      "  - VEGETARIAN = zero meat, fish, seafood, not even in broth or sauce. Also zero animal-derived products used in production: parmesan contains animal rennet (not vegetarian), anchovies are fish (not vegetarian).",
      "  - VEGAN = zero animal products whatsoever.",
      "  - HALAL = zero pork, zero alcohol in cooking.",
      "  - KETO = zero sugar, zero starchy carbs.",
      "  - GLUTEN-FREE = zero gluten in any form.",
      "Before proposing ANY dish, mentally scan EVERY ingredient against EVERY guest's allergies, dislikes AND diet. This includes garnishes, dressings, and minor components.",
      "",
      "THINK BEFORE YOU PROPOSE: Before writing ANY dish name, silently validate it against ALL guest profiles. If it fails, discard it and find another — silently. NEVER write a dish name and then say it is invalid. NEVER write 'let me recalibrate'. NEVER show your thinking process. Only output the final valid dish.",
      "",
      "IMPORTANT: Fish (branzino, daurade, turbot, salmon) is NOT the same as crustacés. Crustacés = shrimp, lobster, crab, shellfish only.",
      "",
      "═══════════════════════════════════════",
      "DISH COHERENCE RULES:",
      "═══════════════════════════════════════",
      "",
      "- ONE dish for the whole table. The dish name must be IDENTICAL for all guests.",
      "- If a vegetarian is at the table, the BASE dish must be vegetarian-friendly. Non-vegetarians may have a protein on the side.",
      "- NEVER propose meat or fish as the main base when a vegetarian guest is present.",
      "- GOOD: Base = Truffle risotto (vegetarian). Arthur & Charlotte get chicken on the side.",
      "- BAD: Base = Wagyu beef. 'For Chloé, a salad instead.' — WRONG.",
      "- Only MINOR adaptations allowed: sauce on the side, garnish removed, protein swap.",
      "- If a forbidden ingredient is EASILY REMOVABLE (e.g. tomatoes in a salad), keep the dish and note the adaptation: '✓ Chloé — no tomatoes'.",
      "- If a forbidden ingredient is CORE TO THE DISH, the dish is INVALID — choose another.",
      "- ONLY mention an adaptation if the ingredient appears EXPLICITLY in the guest's allergy, dislike or diet list. Nothing else justifies an adaptation.",
      "- Do NOT infer restrictions from cuisine preferences. Do NOT assume. Do NOT interpret.",
      "- If an ingredient is not on a guest's forbidden list, they eat it. No adaptation needed.",
      "- ONLY mention an adaptation for a guest if there is a REAL conflict with their restrictions. If a guest has no issue with an ingredient, do not modify their dish.",
      "- Never invent adaptations. If risotto works perfectly for everyone, write '✓ Arthur — no changes'.",
      "- Adaptations must be justified by an actual allergy or dislike listed above. No adaptation without a real reason.",
      "- If no changes: write ONLY '✓ [name] — no changes'. Nothing else. No parentheses, no clarifications.",
      "",
      "═══════════════════════════════════════",
      "MENU GENERATION RULES:",
      "═══════════════════════════════════════",
      "",
      "- When asked to generate a menu, ONLY generate LUNCH and DINNER. Never include breakfast.",
      "- Breakfast preferences are handled separately by the crew.",
      "- Ensure variety across the week: no repeated dishes, balance between land and sea.",
      "- All dishes must be refined, elegant, worthy of a Michelin-starred restaurant.",
      "- Use premium ingredients: truffle, wagyu, langoustine, caviar, premium fish, foie gras.",
      "- Think plating and visual elegance — superyacht guests expect the highest standards.",
      "- Draw inspiration from French, Japanese and Mediterranean haute cuisine.",
      "",
      "═══════════════════════════════════════",
      "SHOPPING LIST RULES:",
      "═══════════════════════════════════════",
      "",
      "- Generate a complete organised list by category with exact quantities.",
      "- Never include forbidden ingredients.",
      "- Categories: Proteins, Vegetables & Fruits, Dairy, Dry Goods, Beverages & Spirits, Herbs & Spices, Condiments.",
      "",
      "═══════════════════════════════════════",
      "RESPONSE FORMAT for dish validation:",
      "═══════════════════════════════════════",
      "",
      "1. [APPROVED] / [NOT RECOMMENDED] / [ADJUST]",
      "2. Dish name — one line",
      "3. One line per guest: '✓ Arthur — no changes' or '✓ Charlotte — dressing on the side'",
      "4. One sentence of explanation maximum",
      "",
      "Keep responses SHORT. The chef reads this in 5 seconds between two pans.",
    ].join("\n")
  }

  const cleanText = (text) => {
    return text
      .replace(/\[APPROVED\]|\[NOT RECOMMENDED\]|\[ADJUST\]/g, '')
      .replace(/\|.+\|/g, '')
      .replace(/^#{1,3} (.+)$/gm, '<div style="font-family:Cormorant Garamond,serif;font-size:18px;font-weight:500;margin:16px 0 6px;color:#1a3a5c;">$1</div>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^[-•] (.+)$/gm, '<div style="display:flex;gap:8px;margin:3px 0;"><span style="color:#1a3a5c;flex-shrink:0;">—</span><span>$1</span></div>')
      .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #e8e0d5;margin:12px 0;"/>')
      .replace(/\n\n/g, '<div style="margin-top:10px;"></div>')
      .replace(/\n/g, '<br/>')
      .trim()
  }

  const sendMsg = async (preset) => {
    if (isLoading || selectedGuests.length === 0) return
    const text = preset || chatInput.trim()
    if (!text) return
    setChatInput('')
    const updatedHistory = [...chatHistory, { role: "user", content: text }]
    setChatHistory(updatedHistory)
    setMessages(prev => [...prev, { role: 'user', text }])
    setIsLoading(true)
    try {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": ANTHROPIC_KEY,
          "anthropic-version": "2023-06-01",
          "anthropic-dangerous-direct-browser-access": "true"
        },
        body: JSON.stringify({ model: "claude-sonnet-4-6", max_tokens: 4000, system: buildSystem(), messages: updatedHistory })
      })
      const data = await res.json()
      if (data.error) throw new Error(data.error.message)
      const reply = (data.content || []).map(b => b.text || "").join("")
      setChatHistory(prev => [...prev, { role: "assistant", content: reply }])
      setMessages(prev => [...prev, { role: 'ai', text: reply }])
    } catch(e) {
      setMessages(prev => [...prev, { role: 'ai', text: '⚠️ ' + e.message }])
    }
    setIsLoading(false)
  }

  const getVerdict = (text) => {
    if (text.includes('[APPROVED]')) return { cls: 'green', label: '✅ Approved' }
    if (text.includes('[NOT RECOMMENDED]')) return { cls: 'red', label: '❌ Not Recommended' }
    if (text.includes('[ADJUST]')) return { cls: 'yellow', label: '⚠️ Adjust' }
    return null
  }

  if (!unlocked) {
    return (
      <>
        <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet"/>
        <nav>
  <svg width="160" height="32" viewBox="0 0 300 60" xmlns="http://www.w3.org/2000/svg">
  <text x="150" y="38" textAnchor="middle" fontFamily="Cormorant Garamond, Georgia, serif" fontSize="28" fontWeight="300" fill="#ffffff" letterSpacing="8">NAUVILUS</text>
  <line x1="40" y1="46" x2="260" y2="46" stroke="#c9a96e" strokeWidth="0.8"/>
</svg>
</nav>
        <main style={{display:'flex',alignItems:'center',justifyContent:'center',minHeight:'60vh'}}>
          <div style={{width:'100%',maxWidth:'360px'}}>
            <div className="page-header" style={{textAlign:'center'}}>
              <h1>Crew <em>Access</em></h1>
              <p>Enter your crew password to continue.</p>
            </div>
            <div className="field" style={{marginTop:'32px'}}>
              <label>Password</label>
              <input type="password" placeholder="Enter crew password" value={passwordInput} onChange={e => { setPasswordInput(e.target.value); setPasswordError(false) }} onKeyDown={e => e.key === 'Enter' && unlock()} style={{borderColor: passwordError ? 'var(--danger)' : undefined}}/>
              {passwordError && <p style={{fontSize:'12px',color:'var(--danger)',marginTop:'6px'}}>Incorrect password. Please try again.</p>}
            </div>
            <button className="btn-primary" onClick={unlock}>Access Crew Dashboard</button>
          </div>
        </main>
      </>
    )
  }

  return (
    <>
      <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet"/>
      <nav>
        <div className="brand">Nauvilus</div>
        {yacht && <span style={{fontSize:'12px',color:'rgba(255,255,255,0.5)',letterSpacing:'.08em'}}>{yacht.name}{activeCharter ? ' · ' + activeCharter.name : ''}</span>}
      </nav>

      <main>
        <div className="page-header">
          <h1>Chef <em>Assistant</em></h1>
          <p>{activeCharter ? `Active charter: ${activeCharter.name}` : 'No active charter. Please set one active in the agency dashboard.'}</p>
        </div>

        {!activeCharter ? (
          <div style={{textAlign:'center',padding:'60px 0',color:'var(--muted)'}}>
            <div style={{fontSize:'32px',marginBottom:'16px'}}>⚓</div>
            <p>No active charter found.<br/>Ask your agency to set a charter as active.</p>
          </div>
        ) : (
          <div className="crew-wrap">
            <div className="guest-card">
              <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:'12px'}}>
                <h3 style={{margin:0}}>Guest Profiles</h3>
                {allGuests.length > 0 && (
                  <button
                    onClick={() => exportGuestsPDF(allGuests, activeCharter?.name)}
                    style={{fontSize:'11px',padding:'5px 10px',background:'transparent',color:'var(--accent)',border:'1px solid var(--accent)',borderRadius:'2px',cursor:'pointer',letterSpacing:'.06em',textTransform:'uppercase'}}
                  >
                    ↓ PDF
                  </button>
                )}
              </div>
              {allGuests.length > 0 && (
                <div style={{display:'flex',gap:'6px',marginBottom:'12px'}}>
                  <button onClick={selectAll} style={{flex:1,padding:'6px',fontSize:'11px',letterSpacing:'.06em',textTransform:'uppercase',background:'var(--accent)',color:'#fff',border:'none',borderRadius:'2px',cursor:'pointer'}}>Select All</button>
                  <button onClick={clearSelection} style={{flex:1,padding:'6px',fontSize:'11px',letterSpacing:'.06em',textTransform:'uppercase',background:'transparent',color:'var(--muted)',border:'1px solid var(--border)',borderRadius:'2px',cursor:'pointer'}}>Clear</button>
                </div>
              )}
              {allGuests.length === 0 ? (
                <div className="no-guest">
                  <div className="ico">👤</div>
                  <p>No guest profiles yet for this charter.</p>
                </div>
              ) : (
                allGuests.map(g => (
                  <GuestCard
                    key={g.id}
                    g={g}
                    isSelected={!!selectedGuests.find(s => s.id === g.id)}
                    onToggle={() => toggleSelectGuest(g)}
                  />
                ))
              )}
            </div>

            <div className="chat-panel">
              <div className="chat-msgs" ref={chatBoxRef}>
                {messages.length === 0 && (
                  <div className="chat-welcome">
                    <div className="ico">🍽️</div>
                    <h3>Good evening, Chef</h3>
                    <p>{selectedGuests.length > 0 ? `Analysing for ${selectedGuests.length} guest${selectedGuests.length > 1 ? 's' : ''}. Propose a dish or ask for a menu.` : 'Select one or more guest profiles to begin.'}</p>
                  </div>
                )}
                {messages.map((msg, i) => {
                  const verdict = msg.role==='ai' ? getVerdict(msg.text) : null
                  return (
                    <div key={i} className={`msg ${msg.role}`}>
                      <div className="avatar">{msg.role==='user' ? '👨‍🍳' : '🤖'}</div>
                      <div className="bubble">
                        {verdict && <div className={`verdict ${verdict.cls}`}>{verdict.label}</div>}
                        {msg.role==='ai'
                          ? <div dangerouslySetInnerHTML={{__html: cleanText(msg.text)}}/>
                          : <div>{msg.text}</div>
                        }
                      </div>
                    </div>
                  )
                })}
                {isLoading && (
                  <div className="msg ai">
                    <div className="avatar">🤖</div>
                    <div className="bubble"><div className="typing"><span></span><span></span><span></span></div></div>
                  </div>
                )}
              </div>
              <div className="chat-input-row">
                <input placeholder="e.g. Truffle risotto tonight?" value={chatInput} onChange={e => setChatInput(e.target.value)} onKeyDown={e => e.key==='Enter' && sendMsg()} disabled={selectedGuests.length === 0}/>
                <button className="send-btn" disabled={isLoading || selectedGuests.length === 0} onClick={() => sendMsg()}>↑</button>
              </div>
              <div className="suggestions">
                {["Truffle risotto tonight?","Full week menu plan?","Shopping list for 7 days?","Dessert ideas?"].map(s => (
                  <button key={s} className="sug" onClick={() => sendMsg(s)} disabled={selectedGuests.length === 0}>{s}</button>
                ))}
              </div>
            </div>
          </div>
        )}
      </main>
    </>
  )
}